import { Inter } from 'next/font/google'
 
// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })

import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} sm:bg-[#1c1c1c] h-screen sm:p-5 transition-all duration-300`}
      >
        <div className=" flex justify-center items-center bg-white w-full h-full p-5 rounded-2.5">
          {children}
        </div>
      </body>
    </html>
  );
}
